version: "3.7"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: '7.2.x-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./app:/var/www/html
      - ./tests:/var/www/tests
  redis:
    container_name: 'sc-redis'
    image: redis:latest
    ports:
      - "6379:6379"
